server:
  port:  8081
spring:
  data:
    mongodb:
      host:  localhost
      port:  27017
      database:  induction
        
# configure eureka client
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 3
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


    
# give the application a name
